spring:
  application:
    name: config-server

    # git配置管理
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chubenli/spring_could_demo.git
          searchPaths: tree/master/config_server/src/main/resources
          username: username
          password: password


server:
  port: 7001
